### ISSUE TITLE
sub-sampling fails with DigitalOutput

### ISSUE THREAD

**Issue by glyg** [ni/nidaqmx-python#116]
Hi,
Thank you for providing an opensource python API to you cards!

I'm using a PCIe 6363 card. Analog outpu controls voltage channels, and I want to use a digital output to drive a TTL. 
With the analog output, I can write more samples than the clock samples per channel, but this fails with the digital output.

Here is a minimal example reproducing the problem:

```python
import nidaqmx
from nidaqmx.constants import (
    LineGrouping)

import numpy as np

with nidaqmx.Task() as task:
    task.ao_channels.add_ao_voltage_chan(
        'Dev1/ao0')

    task.timing.cfg_samp_clk_timing(
            rate=100,
            source="/Dev1/Ctr3InternalOutput",
            samps_per_chan=1000,
            active_edge=nidaqmx.constants.Edge.RISING,
        )

    print('Subsampling an Analog Output works')
    print(task.write(np.ones(10000, dtype=np.uint16)))

with nidaqmx.Task() as task:
    task.do_channels.add_do_chan(
        'Dev1/port0/line0')

    task.timing.cfg_samp_clk_timing(
            rate=100,
            source="/Dev1/Ctr3InternalOutput",
            samps_per_chan=1000,
            active_edge=nidaqmx.constants.Edge.RISING,
        )
    print("subsampling a Digital Output fails: ")
    print(task.write(np.ones(10000, dtype=bool)))
```
And here is the error message I get:

```python-traceback
Traceback (most recent call last):
  File "c:\Users\mosaic\src\quick_test.py", line 32, in <module>
    print(task.write(np.ones(10000, dtype=bool)))
  File "C:\Users\mosaic\Miniforge3\envs\endoscopy-dev\lib\site-packages\nidaqmx\task.py", line 1250, in write
    return _write_digital_lines(
  File "C:\Users\mosaic\Miniforge3\envs\endoscopy-dev\lib\site-packages\nidaqmx\_task_modules\write_functions.py", line 252, in _write_digital_lines
    check_for_error(error_code)
  File "C:\Users\mosaic\Miniforge3\envs\endoscopy-dev\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: The generation is not yet started, and not enough space is available in the buffer.
Configure a larger buffer, or start the generation before writing more data than will fit in the buffer.
Property: DAQmx_Write_RelativeTo
Corresponding Value: DAQmx_Val_CurrWritePos
Property: DAQmx_Write_Offset
Corresponding Value: 0
Property: DAQmx_Buf_Output_BufSize
Corresponding Value: 1000

Task Name: _unnamedTask<1>

Status Code: -200293
```

I'm not very familiar with nidaqmx, so maybe I'm missing something obvious! Is there a workaround? I saw [this thread](https://forums.ni.com/t5/Multifunction-DAQ/How-to-flush-output-buffer-optionally-resize-it-and-write-to-it/td-p/3138640?profile.language=fr) that seems related, but am not sure how to implement the proposed workaround.

Best,

Guillaume

**Comment by glyg** [comment]
Hi, 

Sorry to insist, but can someone at NI look into that?

Best,

Guillaume

**Comment by glyg** [comment]
For information if someone comes across this message, doing the subsampling "by hand" before the write operation seams to do the trick

**Comment by zhindes** [comment]
This is a general NI-DAQmx problem and not an issue with the `nidaqmx` Python bindings. Consider posting on https://forums.ni.com/ for help resolving issues such as this.
