### ISSUE TITLE
Sporadic Status Code: -200473

### ISSUE THREAD

**Issue by mfkeles** [ni/nidaqmx-python#205]
I keep getting this error randomly when I try to trigger a device while recording the trigger output. My aim is to trigger ai when ao is starting and then shut this down on demand and grab the triggered amount of data. However, I keep getting the following error randomly (code works sometimes without an error):

```Exception ignored on calling ctypes callback function: <bound method DAQ.callback of <DAQ.DAQ object at 0x000001A1BA22DBE0>>
Traceback (most recent call last):
  File "C:\Users\sleepdata\PycharmProjects\CameraSetup38\DAQ.py", line 115, in callback
    self.analogMultiChannelReader_.read_many_sample(buffer, samples, timeout=constants.READ_ALL_AVAILABLE)
  File "C:\Users\sleepdata\anaconda3\envs\CameraSetup38\lib\site-packages\nidaqmx\stream_readers.py", line 331, in read_many_sample
    return _read_analog_f_64(
  File "C:\Users\sleepdata\anaconda3\envs\CameraSetup38\lib\site-packages\nidaqmx\_task_modules\read_functions.py", line 31, in _read_analog_f_64
    check_for_error(error_code, samps_per_chan_read=samps_per_chan_read.value)
  File "C:\Users\sleepdata\anaconda3\envs\CameraSetup38\lib\site-packages\nidaqmx\errors.py", line 192, in check_for_error
    raise DaqReadError(error_buffer.value.decode("utf-8"), error_code, samps_per_chan_read)
nidaqmx.errors.DaqReadError: Read cannot be performed when the Auto Start property is false and the task is not running or committed.
Start the task before reading, or set Auto Start to true.
Property: DAQmx_Read_AutoStart
Corresponding Value: 0
Task Name: _unnamedTask<0>
Status Code: -200473
```

Here is the code I used to generate this class 
``` python
import numpy
import copy
import nidaqmx
import nidaqmx.constants as constants
import nidaqmx.stream_readers as stream_readers
import nidaqmx.stream_writers as stream_writers
import numpy as np
import threading


class DAQ:
    """Wrapper class to have easy access to NIDAQ. Allows continuous read/write tasks.
        code modified from:
        https://github.com/TheRandomWalk/Mechanical-Timepiece-Vibration-Analysis/blob/c8a23606a601ef8fbb291d76832326eb442dfa0d/Code/DAQ.py"""

    def __init__(self, samplingRate, bufferSize):
        self.read_task_ = nidaqmx.Task()
        self.write_task_ = nidaqmx.Task()
        self.samplingRate = samplingRate
        self.bufferSize = bufferSize
        self.state = 0
        self.counter = None
        self.data_ = []
        self.threads = []

    @staticmethod
    def _generate_sample(fs, step_dur=3, num_steps=11, min_v=0, max_v=5):
        arr = np.ones(fs * step_dur)
        finarr = np.dot(np.reshape(arr, (arr.size, 1)),
                        np.reshape(np.linspace(min_v, max_v, num_steps), (1, num_steps)))
        signal = np.reshape(np.transpose(finarr), (arr.size * num_steps,))

        # add 30 seconds of full power to the end in case
        sample = np.append(signal, np.ones(fs * 30) * max_v)

        return sample

    def __del__(self):
        self.read_task_.close()
        self.write_task_.close()

    def _create_ao_chan(self):
        self.write_task_.ao_channels.add_ao_voltage_chan('Dev2/ao0')
        self.send_signal = self._generate_sample(self.samplingRate)
        self.write_task_.timing.cfg_samp_clk_timing(rate=self.samplingRate,
                                                    sample_mode=constants.AcquisitionType.CONTINUOUS,
                                                    samps_per_chan=self.send_signal.size)

    def _create_ai_chan(self):
        self.read_task_.ai_channels.add_ai_voltage_chan("Dev2/ai0")
        self.read_task_.timing.cfg_samp_clk_timing(rate=self.samplingRate,
                                                   sample_mode=constants.AcquisitionType.CONTINUOUS,
                                                   samps_per_chan=self.bufferSize)
        self.analogMultiChannelReader_ = stream_readers.AnalogMultiChannelReader(self.read_task_.in_stream)
        self.read_task_.register_every_n_samples_acquired_into_buffer_event(self.bufferSize, self.callback)
        self.mutex_ = threading.Lock()

    def setup_chans(self):
        self._create_ai_chan()
        self._create_ao_chan()

    def synchronized_start(self):
        # ao expects ai to start
        self.write_task_.triggers.start_trigger.cfg_dig_edge_start_trig(self.read_task_.triggers.start_trigger.term)

        self.writer = stream_writers.AnalogSingleChannelWriter(self.write_task_.out_stream, auto_start=False)
        self.writer.write_many_sample(self.send_signal)

        self.write_task_.start()
        self.read_task_.start()

        try:
            bool_task = self.read_task_.is_task_done()
            if bool_task:
                self.read_task_.start()
        except Exception as e:
            print('Read task is not started' , e)
            self.read_task_.start()
        self.data_ = []

    def synchronized_stop(self):
        self.write_task_.stop()
        zeroIt = np.zeros(10)
        self.writer.write_many_sample(zeroIt)

        # disable trigger
        self.write_task_.triggers.start_trigger.disable_start_trig()
        self.write_task_.start()
        self.write_task_.stop()

        # grab the data
        data = self.download()
        self.read_task_.stop()

        return data

    def download(self):
        self.mutex_.acquire()
        data = copy.deepcopy(self.data_)
        self.data_ = []
        self.mutex_.release()
        return data

    def callback(self, taskHandle, eventType, samples, callbackData):
        buffer = numpy.zeros((1, samples))
        self.analogMultiChannelReader_.read_many_sample(buffer, samples, timeout=constants.READ_ALL_AVAILABLE)
        self.mutex_.acquire()
        self.data_.extend(buffer.tolist()[0])
        self.mutex_.release()
        return 0
```

Here is how I use it in my script. It is waiting for a keyboard input and triggers an external device

``` python
import os
import time
from datetime import datetime
import threading
import EasyPySpin
import cv2
import queue
import numpy as np

import DAQ
import events
import writer

daq_data_queue = queue.Queue()
def threaded_start():
    daq.synchronized_start()


def threaded_stop():
    daq_data = daq.synchronized_stop()
    daq_data_queue.put(daq_data)


# A simple script to record video data using FLIR cameras and trigger a laser on demand
folderPath = r'C:\Users\sleepdata\Desktop\ArousalThreshold'

# ===============================================================================
# nidaq related variables
# Sampling Rate for DAQ
fs = 1000

# Buffer size to grab
buffer = 100

# Initiate DAQ and setup channels only done once!
daq = DAQ.DAQ(fs, buffer)
daq.setup_chans()

t = time.localtime()
timestamp = time.strftime('%b-%d-%Y_%H%M', t)

# Use to prevent turning on Laser
evaluation_mode = False

# initiate events object to keep track of output data
events = events.events(folderPath, timestamp)

# Create capture object
cap = EasyPySpin.VideoCapture('21156756')

# Init display font and timeout counters
font = cv2.FONT_HERSHEY_SIMPLEX
delay_counter = 0
movement_persistent_counter = 0

frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
size = (frame_width, frame_height)
cap.set(cv2.CAP_PROP_FPS, 30)
print(f"camera resolution: ({frame_width}x{frame_height})")

full_file_name = os.path.join(folderPath, f"video-{timestamp}.mp4")

video_writer = writer.initiate_videowriter(full_file_name, frame_width, frame_height, fps=30)

# index of the frame
idx = 0

while True:
    start = time.time()

    # Read frame
    ret, frame = cap.read()
    text = "Unoccupied"

    # Interrupt trigger by pressing q to quit the open CV program, write to data frame and check if frame is empty or
    # not
    ch = cv2.waitKey(1)
    if frame is None or ch & 0xFF == ord('q'):
        events.save_outputs()
        break
    elif ch & 0xFF == ord('o'):
        # initiate daq
        daq.state = 1
        t1 = threading.Thread(target=threaded_start)
        t1.start()
        daq.counter = idx
        events.daq_event.append(idx)
        print('Laser ON')
    elif ch & 0xFF == ord('s'):
        if daq.state == 1:
            t2 = threading.Thread(target=threaded_stop)
            t2.start()
            # if not daq_data_queue.empty():
            events.daq_data = daq_data_queue.get()
            daq.state = 0
            events.daq_event.append(idx)
            events.daq_event.append(events.daq_data)
            events.daq_event_list.append(events.daq_event)
            events.daq_data = []
            events.daq_event = []
            print("Laser OFF")

    # If there's an error in capturing
    if not ret:
        print("CAPTURE ERROR")
        continue

    # capture the frame
    video_writer.send(frame)

    # Splice the two video frames together to make one long horizontal one
    cv2.imshow("frame", frame)

    idx += 1

# Cleanup when closed
if daq.state == 1:
    daq.synchronized_stop()
    daq.__del__()

cap.release()
video_writer.close()
cv2.waitKey(0)
cv2.destroyAllWindows()
daq.__del__()
```

As you can see I am using threading to run some of the DAQ related functions (I thought this would fix it but nada). Thank you and  any help is appreciated!

**Comment by zhindes** [comment]
Hmm, when are you getting the error? While the program is running continuously, or when you stop (hit the `s` key)? If its when you stop, my best guess is that there is an in-flight read callback that fires after you have stopped already. in that case, your best bet is to just ignore that error.

The DAQmx Python API sits on top of the DAQmx C API, which should log to [NI I/O Trace](https://www.ni.com/docs/en-US/bundle/ni-io-trace/page/iotrace/iotraceoverview.html). To get a better sense of the exact sequence of events, you can use that to log the DAQmx calls that are happening. With that log, we should be able to tell what went wrong. I doubt this issue is specific to the Python bindings, but that log will help confirm. If that is the case, the best place to get feedback and guidance on your program is the [Multifunction DAQ Forum on ni.com](https://forums.ni.com/t5/Multifunction-DAQ/bd-p/250).
