### ISSUE TITLE
Hardware failure after many reads with hardware-timing

### ISSUE THREAD

**Issue by williamsnider** [ni/nidaqmx-python#446]
Hello, I'm having an issue where I get a hardware failure after doing many reads. Here's the minimal version of the script:
```
import nidaqmx
import nidaqmx.constants

SR = 40000
num_samps_per_chan = 100

with nidaqmx.Task("hw_task") as hw_task:
    hw_task.di_channels.add_di_chan("Dev2/port0/line0")
    hw_task.timing.cfg_samp_clk_timing(
        SR,
        sample_mode=nidaqmx.constants.AcquisitionType.FINITE,
        samps_per_chan=num_samps_per_chan,
    )

    for count in range(100000):
        print("*" * 10)
        print("Loop Count {}: before read line. ".format(count))
        output = hw_task.read(number_of_samples_per_channel=num_samps_per_chan)
        print("Loop Count {}: after read line. ".format(count))
        hw_task.wait_until_done()
        print("Loop Count {}: after wait_until_done. ".format(count))

```
Here's the output when the error occurs: 
```
**********
Loop Count 5754: before read line. 
Loop Count 5754: after read line. 
Loop Count 5754: after wait_until_done. 
**********
Loop Count 5755: before read line. 
Loop Count 5755: after read line. 
Loop Count 5755: after wait_until_done. 
**********
Loop Count 5756: before read line. 
Loop Count 5756: after read line. 
Loop Count 5756: after wait_until_done. 
**********
Loop Count 5757: before read line. 
Traceback (most recent call last):
  File "/home/oconnorlabmatlab/Code/nidaq/examples/minimal.py", line 20, in <module>
    output = hw_task.read(number_of_samples_per_channel=num_samps_per_chan)
  File "/home/oconnorlabmatlab/miniconda3/envs/robot_venv/lib/python3.9/site-packages/nidaqmx/task.py", line 675, in read
    samples_read = _read_digital_lines(
  File "/home/oconnorlabmatlab/miniconda3/envs/robot_venv/lib/python3.9/site-packages/nidaqmx/_task_modules/read_functions.py", line 345, in _read_digital_lines
    check_for_error(error_code, samps_per_chan_read=samps_per_chan_read.value)
  File "/home/oconnorlabmatlab/miniconda3/envs/robot_venv/lib/python3.9/site-packages/nidaqmx/errors.py", line 179, in check_for_error
    raise DaqReadError(error_buffer.value.decode("utf-8"), error_code, samps_per_chan_read)
nidaqmx.errors.DaqReadError: A hardware failure has occurred. The operation could not be completed as specified.
Task Name: hw_task

Status Code: -50152
```

How can I troubleshoot this?

**Comment by bkeryan** [comment]
This sounds a lot like https://github.com/ni/nidaqmx-python/issues/417 (error -50152 on Linux). Try the troubleshooting steps and solution from that issue and see if it solves your problem.

Note that your program reserves and commits the task for each loop iteration, which requires the DAQmx driver to do extra work, such as allocating and deallocating the task's circular buffer. Calling `hw_task.control(TaskMode.TASK_COMMIT)` before the loop would avoid this extra work, and if the problem is intermittent, it could potentially work around the problem.

For non-Python-specific issues with the DAQmx driver and hardware, I'd recommend the [Multifunction DAQ board on ni.com](https://forums.ni.com/t5/Multifunction-DAQ/bd-p/250) for future support.
