### ISSUE TITLE
nidaqmx doesn't support Python 3.13+

### ISSUE THREAD

**Issue by zhindes** [ni/nidaqmx-python#644]
To reproduce:
* Install Python 3.13
* `pip install nidaqmx`
* Run some of the shipping examples

At the very least I ran into this:
```
Traceback (most recent call last):
  File "C:\Users\User\dev\junyinta-nimbus-benchmark\ramp_up.py", line 5, in <module>
    import nidaqmx
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\benchmark-PLHonyti-py3.13\Lib\site-packages\nidaqmx\__init__.py", line 3, in <module>
    from nidaqmx.scale import Scale
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\benchmark-PLHonyti-py3.13\Lib\site-packages\nidaqmx\scale.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

That is because our numpy dependency excludes Python 3.13+ [here](https://github.com/ni/nidaqmx-python/blob/41cb6ba35c0781dec34d2e4fc91e23b22b813135/pyproject.toml#L35). There may be other issues, though. We should officially support and test Python 3.13+

**Comment by bkeryan** [comment]
Oops, I should have made that an open-ended range or capped it at 4.0 like I did for grpcio-tools: https://github.com/ni/nidaqmx-python/pull/453/

**Comment by bkeryan** [comment]
Note that we need to add Python 3.13 to the nidaqmxbot image build config.
